name: "Compile LaTeX Poster"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Compile"
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "root.tex"
          working_directory: "20260725中間発表①"
          # ↓ compiler を指定せず、latexmk を使う設定にします
          latexmk_use_lualatex: true 
          # ↓ latexmk を使う場合は、args ではなくこれを使います
          latexmk_shell_escape: true

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: "Poster-PDF-${{ github.ref_name }}"
          # ↓ ここも自分のフォルダ名を含める
          path: "20260725中間発表①/root.pdf"